language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: brokermanagement-dev
  api_key:
    secure: SNm0K/gwbbrO2HFLWjhe9I+Gkd3CdbM7Np3ABdEzqfUHrA2vt9W637av14WCsOyTkNQa6ODe56uXtmYFppq0L1kUAcpUxwP2FdtdLY1wowfdaVf9wo2RdYs+CSS59eJh/OwDZNqlQguCug6vLKXWEZxaQnHN3sagryxCPh6i/VnZfxSLNORTwMJTT41+6/7mZc2Bd6Ne5CHH8QJouhJILxuFiUrBo1HxK9xm7zuZ3j//cVyZ87am5P8gFW1yl3q9h+Ieaw8zzT9HfOk3q+2YogAhkoIcPeySalXb0fw4P6RlfB49udtNtti847qJf64mO+5FRcX+ppwoO1R9JOl80WiLAxyTHaRzNT4GhK1jwnRI1zVin2W+y9Vz7GNJQldwDJcmnelclWbqEFDKb7xro8J1yqNdmvuKN1doyQppZwkYVx+Tlax68VrTVlppA7Hdon8o5jRZKpCR6mJQHNjCQu9+DK6YEWNLysqWJjmEh91NZ9aB3g8g1EtS5YJHfmVYQXGDFahGxGocmQJLLoj/sjne6L8lcgF1V+/SHK6AsNsR8LxzysAL5iLm5TZ8NJwJu6x9c4lh3+cM0NWysfgrlw2lobkcur0zCrRf1ZDCnOZ6/Cb9FDydCmFgobHjXVedFMEBllkhBk8jNeh/Ypux9nk1aPsxuuskabRi+S+VzFs=
